Languages/kotlin
sequenia/CleanCode pull request #1
Opened 2022-02-15 04:55 UTC by 4ybakut2004

2022-02-15 09:45 UTC, foxaice requested changes

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +        return DateTimeFormatter.ofPattern(ff)
DateTimeFormatter.ofPattern(ff) -> DateTimeFormatter.ofPattern(format)

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +const val GRAVITATION_CONSTANT: Float = 9.81f
\<zanuda mode on>
earth gravity acceleration
\<zanuda mode off>

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +// Или
-> // Или воспользоваться именованными параметрами

а то "// Или" как-то скудно выглядит по сравнению со всем остальным текстом)

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +- При вызове функции трудно определить, за что отвечают похожие по типу не именованные аргументы.
не именованные -> неименованные

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +fun getTotalAmount(): Int? {
хм.. чёт где явно this указывается, а где-то нет. Может к одному виду привести?

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +fun getTotalAmount(): Int? {
это лишь вопрос)

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +        return "Email: " + admin.email + "\n" +
тут "user" лучше заюзать)

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +    protected fun getFirstName(PersonalInfo personalInfo): String {
"PersonalInfo personalInfo" -> это же kotlin! 😂

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +    protected fun getFirstName(PersonalInfo personalInfo): String {
ниже также)

2022-02-15 09:45 UTC, foxaice commented on languages/KOTLIN.md
> +- Вместо покрытия кода комментариями пытайтесь отраизить свои намерения в коде с помощью продуманного именования, введения промежуточных переменных и функций.
"отраизить" -> отразить

2022-06-21 10:18 UTC, 4ybakut2004 commented on languages/KOTLIN.md
> +const val GRAVITATION_CONSTANT: Float = 9.81f
Если исправлять, то на "GRAVITATIONAL_CONSTANT" - https://en.wikipedia.org/wiki/Gravitational_constant

2022-06-21 10:29 UTC, 4ybakut2004 commented on languages/KOTLIN.md
> +// Или
В котлине именованными могут быть аргументы, а не параметры) Но да, заменю :+1:

2022-06-21 10:33 UTC, 4ybakut2004 commented on languages/KOTLIN.md
> +fun getTotalAmount(): Int? {
Да, вышла путаница. Приведу к одному виду.

2022-06-21 10:34 UTC, 4ybakut2004 commented on languages/KOTLIN.md
> +        return "Email: " + admin.email + "\n" +
Действительно XD

2022-06-21 10:36 UTC, 4ybakut2004 commented on languages/KOTLIN.md
> +    protected fun getFirstName(PersonalInfo personalInfo): String {
Да кого это волнует XD

2022-06-22 02:39 UTC, merged